var questions = [
  //1. fejezet - Bevezetés
  { question: "A PAN kisebb hálózatot jelent mint a MAN.", answer: true, hint: "PAN < LAN < MAN < WAN < INTERNET"},
  { question: "A MAN kisebb hálózatot jelent mint a PAN.", answer: false, hint: "PAN < LAN < MAN < WAN < INTERNET"},
  { question: "Az elosztott rendszerekben lévő gépeket egy közös operációs rendszer fogja össze.", answer: true, hint: "Pedig ez igaz :D"},
  { question: "A klasszikus hálózat autonóm gépekből áll.", answer: true, hint: "Pedig ez igaz :D"},
  { question: "Az elosztott rendszerek autonóm gépekből állnak.", answer: false, hint: "A klasszikus hálózat áll autonóm gépekből."},
  { question: "Az elosztott rendszert az átlag felhasználó jellemzően egy gépnek (erőforrásnak) látja.", answer: true, hint: "Ez igaz."},

  //2. fejezet - Hálózati szoftver
  { question: "A legtöbb ma is használatban lévő hálózati modell réteges (Layer) szerkezetű.", answer: true, hint: "Ez igaz."},
  { question: "Az azonos szintű rétegek a felettük levő rétegek segítségével érik el egymást.", answer: false, hint: "Az azonos szintű rétegek az alattuk levő rétegekkel érik el egymást!"},
  { question: "Az azonos szintű rétegek az alattuk levő rétegek segítségével érik el egymást.", answer: true, hint: "Ez igaz."},
  { question: "Az azonos szintű rétegek közvetlenül elérik egymást.", answer: false, hint: "Ez csak a fizikai rétegre igaz. A többi réteg az alatta levő rétegen keresztül éri el az azonos szinten levő de más hosztnál található réteget."},
  { question: "Az egymással szomszédos rétegek között interfész (Interface) található.", answer: true, hint: "Ez igaz."},
  { question: "A különböző hosztok azonos rétegeit társidentitásoknak (Peer) nevezzük.", answer: true, hint: "Ez igaz."},
  { question: "Az azonos rétegek közötti kommunkiáció szabályai az úgynevezett interfészek.", answer: false, hint: "Azok a protokollok!"},
  { question: "Az azonos rétegek közötti kommunkiáció szabályai az úgynevezett protokollok.", answer: true, hint: "Ez igaz."},
  { question: "Az interface-ekre virtuális kommunikácó jellemző.", answer: false, hint: "Az interface-ek kommunkikácóija 'valódi'."},
  { question: "Az interface egy hoszton belül az egymás alatti rétegek kommunikációja, ami 'valódi' kommunikáció.", answer: true, hint: "Ez igaz."},
  { question: "Az interface különböző hosztok azonos szintjei közötti kommunikáció, ami 'virtuális' kommunikáció.", answer: false, hint: "Ez a protokollok jellemzője."},
  { question: "Az interface különböző hosztok azonos szintjei közötti kommunikáció, ami nem közvetlenül, hanem közvetítő rétegek segítségével valósul meg.", answer: false, hint: "Ez a protokollok jellemzője."},
  { question: "A protokoll különböző hosztok azonos szintjei közötti kommunikáció, ami 'virtuális' kommunikáció.", answer: true, hint: "Ez igaz."},
  { question: "A protokoll különböző hosztok azonos szintjei közötti kommunikáció, ami nem közvetlenül, hanem közvetítő rétegek segítségével valósul meg.", answer: true, hint: "Ez igaz."},
  { question: "A protokoll egy hoszton belül az egymás alatti rétegek kommunikációja, ami 'valódi' kommunikáció.", answer: false, hint: "Ez az interface-ek tulajdonsága."},
  { question: "Az összeköttetés alapú (Connection Oriented Service) rendszer modellezhető például a klaszikus (analóg) telefonhálózattal.", answer: true, hint: "Ez igaz."},
  { question: "Az összeköttetés alapú rendszerre példa a postai levélszolgáltatás.", answer: false, hint: "Ez az összeköttetés nélüli rendszerekre lehet példa."},
  { question: "Az összeköttetés nélküli rendszerre példa a postai levélszolgáltatás.", answer: true, hint: "Ez igaz."},
  { question: "A primitívek - azaz elemi műveletek - rendszerhívások az egyes szolgáltatások eléréséhez.", answer: true, hint: "Ez igaz."},
  { question: "Az összeköttetés alapú protokollnál az összeköttetés lebonyolításához min. 6db áttvitt csomagra (Connect;Accept;Send;Recive;Disconnect;Disconnect) van szükség.", answer: true, hint: "Ez igaz."},
  { question: "Az összeköttetés alapú protokollnál az összeköttetés lebonyolításához min. 7db áttvitt csomagra (Listen;Connect;Accept;Send;Recive;Disconnect;Disconnect) van szükség.", answer: false, hint: "A Listen nem része az átvitelnek."},
  { question: "A szolgáltatás azon primitívek halmaza, amelyeket egy adott réteg a felette levő rétegek számára biztosít.", answer: true, hint: "Ez igaz."},
  { question: "A szolgáltatás azon primitívek halmaza, amelyeket egy adott réteg az alatta levő rétegek számára biztosít.", answer: false, hint: "Egy adott réteg a felette levő rétegek számára biztosít szolgáltatást."},
  { question: "A szolgáltatás két szomszédos réteg közötti interfésszel kapcsolatos.", answer: true, hint: "Ez igaz."},
  { question: "A szolgáltatás különböző hosztok azonos szintjei közötti protokollokkal kapcsolatos.", answer: false, hint: "A szolgáltatás egy hoszton belüli rétegek közötti interfésszel kapcsolatos."},
  { question: "A protokoll olyan szabályok halmaza, amely a 'hogyan' kérdéssel kapcsolatos.", answer: true, hint: "Ez igaz."},
  { question: "A protokoll a szolgáltatás implementációjának felel meg.", answer: true, hint: "Ez igaz."},

  //3. fejezet - Hivatkozási modellek
  { question: "Az OSI modellhez kapcsolódó protokollok ma már gyakorlatilag nem használatosak.", answer: true, hint: "Ez igaz."},
  { question: "Az OSI modellhez kapcsolódó protokollok ma is használatosak.", answer: false, hint: "Ma már gyakkorlatilag nem használják az OSI modell protokolljait, a TCP/IP protokolljai viszont használatban vannak."},
  { question: "A TCP/IP modellt a mai napig az eredeti 4 rétegű megvalósításban használják.", answer: false, hint: "A TCP/IP eredeti 4 rétegű megvalósítása ma már nem használatos, viszont a hozzá definiált protokollok igen."},
  { question: "Az OSI modell 7 rétegből áll.", answer: true, hint: "Ez igaz."},
  { question: "Az OSI modell 4 rétegből áll.", answer: false, hint: "Az OSI modell 7 rétegből áll... a TCP/IP modell áll 4 rétegből."},
  { question: "Az OSI modell 6 rétegből áll.", answer: false, hint: "7 rétegből áll."},
  { question: "Az OSI 'Open System Interconnect' kezdőbetűiből áll.", answer: true, hint: "Ez igaz."},
  { question: "Az OSI 'Open System Interface' kezdőbetűiből áll.", answer: false, hint: "Open System Interconnect"},
  { question: "Az adatkapcsolati réteg (OSI) az adatokat egyértelműen azonosítható adatkeretbe tördeli szét.", answer: true, hint: "Ez igaz."},
  { question: "A keretezés a hálózati réteg (OSI) feladata.", answer: false, hint: "Az adatkapcsolati réteg feladata hogy az adatokat egyértelműen azonosítható adatkeretekbe tördelje szét."},
  { question: "Az adatkapcsolati réteg (OSI) a vevő által küldött nyugtázásokat is feldolgozza.", answer: true, hint: "Ez igaz."},
  { question: "A hálózati réteg (OSI) feladata a keretek forrás- és célállomás közötti útvonalának meghatározása, kiválasztása, azaz a forgalomirányítás.", answer: true, hint: "Ez igaz."},
  { question: "A hálózati réteg (OSI) feladata az adatok adatkeretekbe tördelése.", answer: false, hint: "Az adatok keretezése az adatkapcsolati réteg feladata az OSI modellben."},
  { question: "Az adatkapcsolati réteg (OSI) feladata hogy kétirányú átvitel esetén az esetleges üztközésekből adódó problémákat megoldja.", answer: true, hint: "Ez igaz."},
  { question: "Az adatkapcsolati réteg (OSI) feladata hogy a keretek forrás- és célállomás közötti útvonalát meghatározza, kiválassza, azaz a forgalomirányítás.", answer: false, hint: "Ez a hálózati réteg feladata."},
  { question: "Az adatkapcsolati réteg (OSI) a kereteket vezérlőbitekkel látja el és sorrendben továbbítja azokat.", answer: true, hint: "Ez igaz."},
  { question: "Az úgynevezett torlódási problémával a hálózati rétegnek (OSI) kell szembenéznie.", answer: true, hint: "Ez igaz."},
  { question: "Az úgynevezett torlódási problémával az adatkapcsolati rétegnek (OSI) kell szembenéznie.", answer: false, hint: "Ezt a problémát a hálózati réteg kezeli."},
  { question: "Az adatszóró hálózatokban a hálózati réteg elhagyható.", answer: true, hint: "Ez igaz."},
  { question: "A szállítási réteg (OSI) az adatokat csomagokra bontja szét, ha szükséges.", answer: true, hint: "Ez igaz."},
  { question: "A szállítási réteg (OSI) az adatokat adatkeretekbe tödeli szét, ha szükséges.", answer: false, hint: "A keretezést az adatkapcsolati réteg végzi."},
  { question: "A szállítási réteg (OSI) két végpont közötti réteg (a forrás- és a célállomás egymással kommunikál).", answer: true, hint: "Ez igaz."},
  { question: "A szállítási réteg (OSI) és a fölötti rétegek kommunikációja hoszt-hoszt közötti, virtuális kommunikáció.", answer: true, hint: "Ez igaz."},
  { question: "A szállítási réteg (OSI) feletti rétegek hoszt-hoszt kommunikációja 'valódi kommunikáció.'", answer: false, hint: "A szállítási réteg és a fölötte levő rétegek hoszt-hoszt kommunikációja 'virtuális'."},
  { question: "", answer: true, hint: ""},

  //4. fejezet - A modell és az internet kialakulása

  //5. fejezet - Mobiltelefon hálózatok
  { question: "A 0G mobilhálózat jellemzője az automatikus hívásindítás", answer: false, hint: ""},
  { question: "Az 1G mobilhálózat részben digitális megoldású.", answer: false, hint: ""},
  { question: "A 2.5G mobilhálózat része az UMTS", answer: false, hint: "Az UMTS a 3G-nél jött."},
  { question: "A 3G mobilhálózatnak nem része a WCDMA.", answer: false, hint: "2001-ben, az UMTS (más néven WCDMA) szabványosítása után indult a 3G."},

  //ZH kérdések voltak
  { question: "A mikrohullám visszaverődik az ionoszférából.", answer: false, hint: ""},
  { question: "Az AES a WEP2 védelem algoritmusa", answer: true, hint: ""},
  { question: "Az LDPC kódolás matematikailag polinomokra épül.", answer: false, hint: ""},
  { question: "A csúszóablakos protokoll tartalmaz önálló nyugtakeretet.", answer: true, hint: ""},
  { question: "A DSSS 11db csatornája részben sem fedi át egymást.", answer: false, hint: ""},
  { question: "Egy Switch-ekkel összekötött hálózatban nem fordulhat elő ütközés.", answer: true, hint: ""},
  { question: "A Hamming-távolságot egy NOR művelettel számolhatjuk ki.", answer: false, hint: ""},
  { question: "Az LLC alréteg felel a csatorna kiosztásért.", answer: false, hint: ""},
  { question: "A versenyhelyzetben lévő protokollok nagy terhelésnél teljesítenek jól.", answer: false, hint: ""},
  { question: "A karakterszámlálás egy sérülésvédett keretezési megoldás.", answer: false, hint: ""},
  { question: "Páros paritás esetén a paritásbit 0, ha az 1-esek száma páros.", answer: true, hint: ""},
  { question: "A 256-QAM egyetlen jelváltozással 16 bitet kódol.", answer: false, hint: "A 256-QAM 8 bitet kódol egyetlen jelváltozással."},
  { question: "A p-perzisztens CSMA szabad csatorna esetén azonnal adni kezd.", answer: false, hint: ""},

  { question: "Az IT-ban használt IEC mértékegység alapja a tízes számrendszer.", answer: false, hint: ""},
  { question: "Egy megabájt kisebb, mint egy mebibájt.", answer: true, hint: ""},
  { question: "A bináris rendszer jellemzően háttértár méretre utal.", answer: false, hint: ""},
  { question: "Egy informatikai mérnök számára a sávszélesség mértékegysége a Hz", answer: false, hint: ""},
  { question: "A Shannon tétel az ideális átviteli csatornával kapcsolatos.", answer: false, hint: ""},
  { question: "Az IEEE 802.3 szabványba a 'Base' szó jelentése 'alapvető'.", answer: false, hint: ""},
  { question: "A 'T-568A' és 'T-568B' bekötése 50%-ban megegyezik.", answer: true, hint: ""},
  { question: "Az LSOH/LSZH a kábel mechanikai tesztelésének jelzése.", answer: false, hint: ""},
  { question: "Az NRZ-S kódolást az USB szabvány használja.", answer: false, hint: ""},

  //{ question: "", answer: true, hint: ""},
];
